apiVersion: v1
kind: Service
metadata:
  name: service-greeting-eric-service 
spec:
  ports:
  - port: 30006
    nodePort: 30006
    targetPort: 8080
  selector:
    app: service-greeting-eric
  type: NodePort
